// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: text_analys.proto
#ifndef GRPC_text_5fanalys_2eproto__INCLUDED
#define GRPC_text_5fanalys_2eproto__INCLUDED

#include "text_analys.pb.h"
#include "../../../lib/grpc/include/grpcpp/support/method_handler.h"
#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace Text_analys {

class TextAnalysService final {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status getResult(::grpc::ClientContext* context, const ::Text_analys::SettingsTextPB& request, ::Text_analys::ResultParsingPB* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Text_analys::ResultParsingPB>> AsyncgetResult(::grpc::ClientContext* context, const ::Text_analys::SettingsTextPB& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Text_analys::ResultParsingPB>>(AsyncgetResultRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Text_analys::ResultParsingPB>* AsyncgetResultRaw(::grpc::ClientContext* context, const ::Text_analys::SettingsTextPB& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status getResult(::grpc::ClientContext* context, const ::Text_analys::SettingsTextPB& request, ::Text_analys::ResultParsingPB* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Text_analys::ResultParsingPB>> AsyncgetResult(::grpc::ClientContext* context, const ::Text_analys::SettingsTextPB& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Text_analys::ResultParsingPB>>(AsyncgetResultRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::Text_analys::ResultParsingPB>* AsyncgetResultRaw(::grpc::ClientContext* context, const ::Text_analys::SettingsTextPB& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_getResult_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status getResult(::grpc::ServerContext* context, const ::Text_analys::SettingsTextPB* request, ::Text_analys::ResultParsingPB* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_getResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_getResult() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_getResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getResult(::grpc::ServerContext* context, const ::Text_analys::SettingsTextPB* request, ::Text_analys::ResultParsingPB* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetResult(::grpc::ServerContext* context, ::Text_analys::SettingsTextPB* request, ::grpc::ServerAsyncResponseWriter< ::Text_analys::ResultParsingPB>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_getResult<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_getResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_getResult() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_getResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getResult(::grpc::ServerContext* context, const ::Text_analys::SettingsTextPB* request, ::Text_analys::ResultParsingPB* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_getResult() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::Text_analys::SettingsTextPB, ::Text_analys::ResultParsingPB>(std::bind(&WithStreamedUnaryMethod_getResult<BaseClass>::StreamedgetResult, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_getResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getResult(::grpc::ServerContext* context, const ::Text_analys::SettingsTextPB* request, ::Text_analys::ResultParsingPB* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetResult(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Text_analys::SettingsTextPB,::Text_analys::ResultParsingPB>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_getResult<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_getResult<Service > StreamedService;
};

}  // namespace Text_analys


#endif  // GRPC_text_5fanalys_2eproto__INCLUDED
